

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalContextProvider } from "@/context/initialGeoCode";
import Home from "./page";
import { DataContextProvider } from "@/context/areas";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({ children }: { children: React.ReactNode }) {


  return (
    <html lang="en">
      <body>
        <GlobalContextProvider> <DataContextProvider> {children}</DataContextProvider> </GlobalContextProvider>
      </body>
    </html>
  );
}
